FROM anthesevenants/lingquizticsanalysis:base
# We start from the R Studio base

# Let's set the working directory correctly (also for the R environment itself)
RUN echo "setwd(\"/home/rstudio/lingquiztics-analysis/\")" > ~/../home/rstudio/.Rprofile
RUN mkdir -p "/home/rstudio/.local/share/rstudio/projects_settings/"
RUN chmod -R 777 "/home/rstudio/.local/"
